In [2]:
import pandas as pd
import numpy as np

In [7]:
# Load the movies.csv dataset
df = pd.read_csv('movies.csv')

# Display the first 5 rows of the DataFrame
print("First 5 rows of the dataset:")
display(df.head(10))

First 5 rows of the dataset:

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross
0,Blood Red Sky,(2021),"\nAction, Horror, Thriller",6.1,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,"21,062",121.0,NaN
1,Masters of the Universe: Revelation,(2021– ),"\nAnimation, Action, Adventure",5.0,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...","17,870",25.0,NaN
2,The Walking Dead,(2010–2022),"\nDrama, Horror, Thriller",8.2,\nSheriff Deputy Rick Grimes wakes up from a c...,"\n \n Stars:\nAndrew Lincoln, \n...","885,805",44.0,NaN
3,Rick and Morty,(2013– ),"\nAnimation, Adventure, Comedy",9.2,\nAn animated series that follows the exploits...,"\n \n Stars:\nJustin Roiland, \n...","414,849",23.0,NaN
4,Army of Thieves,(2021),"\nAction, Crime, Horror",NaN,"\nA prequel, set before the events of Army of ...",\n Director:\nMatthias Schweighöfer\n| \n ...,NaN,NaN,NaN
5,Outer Banks,(2020– ),"\nAction, Crime, Drama",7.6,\nA group of teenagers from the wrong side of ...,"\n \n Stars:\nChase Stokes, \nMa...","25,858",50.0,NaN
6,The Last Letter from Your Lover,(2021),"\nDrama, Romance",6.8,\nA pair of interwoven stories set in the past...,\n Director:\nAugustine Frizzell\n| \n S...,"5,283",110.0,NaN
7,Dexter,(2006–2013),"\nCrime, Drama, Mystery",8.6,"\nBy day, mild-mannered Dexter is a blood-spat...","\n \n Stars:\nMichael C. Hall, \...","665,387",53.0,NaN
8,Never Have I Ever,(2020– ),\nComedy,7.9,\nThe complicated life of a modern-day first g...,\n \n Stars:\nMaitreyi Ramakrish...,"34,530",30.0,NaN
9,Virgin River,(2019– ),"\nDrama, Romance",7.4,"\nSeeking a fresh start, nurse practitioner Me...",\n \n Stars:\nAlexandra Breckenr...,"27,279",44.0,NaN

### Dataset Information
Let's check the number of rows and columns, data types, and non-null values.

In [4]:
# Display basic information about the dataset
print("Dataset Info:")
df.info()

Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9999 entries, 0 to 9998
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   MOVIES    9999 non-null   object
 1   YEAR      9355 non-null   object
 2   GENRE     9919 non-null   object
 3   RATING    8179 non-null   float64
 4   ONE-LINE  9999 non-null   object
 5   STARS     9999 non-null   object
 6   VOTES     8179 non-null   object
 7   RunTime   7041 non-null   float64
 8   Gross     460 non-null    object
dtypes: float64(2), object(7)
memory usage: 703.2+ KB

### Descriptive Statistics
Now, let's look at the descriptive statistics for numerical columns.

In [5]:
# Display descriptive statistics
print("Descriptive Statistics:")
display(df.describe())

Descriptive Statistics:

            RATING      RunTime
count  8179.000000  7041.000000
mean      6.921176    68.688539
std       1.220232    47.258056
min       1.100000     1.000000
25%       6.200000    36.000000
50%       7.100000    60.000000
75%       7.800000    95.000000
max       9.900000   853.000000

### Data Type Conversion and Cleaning (YEAR, VOTES, Gross)
To effectively handle missing values, we first need to clean and convert 'YEAR', 'VOTES', and 'Gross' columns to numerical types. This involves extracting numerical data from their string representations and splitting 'YEAR' into start and end years.

In [16]:
import re

def parse_year_range(year_str):
    if pd.isna(year_str):
        return np.nan, np.nan

    year_str = str(year_str).strip()
    # Remove parentheses for easier parsing
    year_str = year_str.replace('(', '').replace(')', '')

    if '–' in year_str: # Handles ranges like '2010–2022' or '2021– '
        parts = year_str.split('–')
        start_year = int(parts[0].strip()) if parts[0].strip() else np.nan
        end_year = int(parts[1].strip()) if parts[1].strip() else np.nan
    else: # Handles single years like '2021'
        start_year = int(year_str.strip()) if year_str.strip() else np.nan
        end_year = start_year # If it's a single year, start and end are the same

    return start_year, end_year

# Apply the function to create new columns
df[['START_YEAR', 'END_YEAR']] = df['YEAR'].apply(lambda x: pd.Series(parse_year_range(x)))

# Convert new columns to integer type, allowing for NaNs
df['START_YEAR'] = df['START_YEAR'].astype('Int64')
df['END_YEAR'] = df['END_YEAR'].astype('Int64')

# Drop the original 'YEAR' column as it's been split
df = df.drop(columns=['YEAR'])

# Clean and convert 'VOTES' column
# Remove commas and convert to float
df['VOTES'] = df['VOTES'].str.replace(',', '', regex=False).astype(float)

# Clean and convert 'Gross' column
# Remove '$', 'M', and commas, then convert to float. Assume 'M' means millions.
def clean_gross(gross_str):
    if pd.isna(gross_str):
        return np.nan
    gross_str = str(gross_str).replace('$', '').replace(',', '')
    if 'M' in gross_str:
        try:
            return float(gross_str.replace('M', '')) * 1_000_000
        except ValueError:
            return np.nan
    else:
        try:
            return float(gross_str)
        except ValueError:
            return np.nan

df['Gross'] = df['Gross'].apply(clean_gross)

print("Data types after cleaning 'START_YEAR', 'END_YEAR', 'VOTES', 'Gross':")
df.info()

print("\nFirst 5 rows after cleaning and conversion:")
display(df.head())

ValueError: invalid literal for int() with base 10: 'I 2018'

### Handling Missing Values: Dropping Rows with NaNs
Now that the relevant columns have been converted to appropriate data types, we can proceed with dropping rows that contain any NaN values. We will first check the number of missing values and the DataFrame shape before and after the operation.

In [ ]:
# Display the number of missing values before dropping
print("Missing values before dropping NaNs:")
display(df.isnull().sum()[df.isnull().sum() > 0])

# Store the original shape of the DataFrame
original_shape = df.shape
print(f"\nOriginal DataFrame shape: {original_shape}")

# Drop rows with any NaN values
df_cleaned = df.dropna().copy()

# Display the new shape of the DataFrame
cleaned_shape = df_cleaned.shape
print(f"Cleaned DataFrame shape after dropping NaNs: {cleaned_shape}")
print(f"Number of rows dropped: {original_shape[0] - cleaned_shape[0]}")

# Display the info of the cleaned DataFrame to confirm no more NaNs
print("\nInfo of cleaned DataFrame:")
df_cleaned.info()

# Display the first few rows of the cleaned DataFrame
print("\nFirst 5 rows of the cleaned DataFrame:")
display(df_cleaned.head())

In [19]:
df[df['YEAR']== '2018']

Empty DataFrame
Columns: [MOVIES, YEAR, GENRE, RATING, ONE-LINE, STARS, VOTES, RunTime, Gross]
Index: []

In [15]:
for x in df['YEAR']:
  print(str(x))

(2021)
(2021– )
(2010–2022)
(2013– )
(2021)
(2020– )
(2021)
(2006–2013)
(2020– )
(2019– )
(2021)
(2016–2021)
(2021)
(2021– )
(2011– )
(2005– )
(2008–2013)
(2017– )
(2017–2021)
(2016– )
(2021)
(1994–2004)
(2014– )
(2013– )
(2021– )
(2021)
(2013–2020)
(2015– )
(2005–2020)
(2013– )
(2021)
(2016– )
(2013–2022)
(2003– )
(2019– )
(2009–2020)
(I) (2018– )
(2019– )
(2010–2015)
(2013–2022)
(2011–2019)
(2017–2021)
(2015–2020)
(2014– )
(2015– )
(2011– )
(2017– )
(2016– )
(2021– )
(2021)
(2014– )
(2005–2014)
(2009–2015)
(2008–2014)
(2016–2018)
(2009–2017)
(2020)
(2019– )
(2018–2021)
(2017–2020)
(2020)
(2016– )
(1987–1994)
(2021)
(2021)
(2019– )
(2015– )
(2018– )
(2012– )
(2014–2020)
(2011–2018)
(2005–2017)
(2019– )
(2021)
(2021– )
(2021– )
(2021– )
(2017)
(2007–2015)
(2018– )
(2000–2007)
(2021– )
(2021– )
(2021)
(II) (2007– )
(1993)
(1999–2022)
(2015–2018)
(2017–2020)
(2016– )
(2018– )
(2019– )
(2014–2019)
(2016– )
(2013–2020)
(2016)
(2021)
(2012–2020)
(2013–2019)
(2007–2012)
(2020– )
(2018–2021)
(2011–2020)
(2017– )
(2010–2017)
(2021)
(2016–2021)
(2000–2015)
(2019– )
(2015–2021)
(2014–2020)
(2001)
(2019– )
(1997– )
(2011–2018)
(2017– )
(2011–2017)
(2014–2020)
(1993–1999)
(1989–1998)
(2010–2013)
(2010–2020)
(2015–2021)
(2017– )
(2003–2019)
(I) (2019)
(2018– )
(2017–2019)
(1975)
(2005–2008)
(2017–2019)
(1995–2001)
(2006)
(2015–2017)
(2021)
(2008–2020)
(1984–1996)
(2021)
(2010– )
(2021– )
(2021)
(2019– )
(2021– )
(2014)
(2017)
(2000)
(2013–2018)
(2015– )
(2021)
(2019– )
(2014–2019)
(2009–2016)
(2016–2020)
(2013–2018)
(2009–2015)
(2021 TV Special)
(2003)
(2021)
(2017–2021)
(2006)
(1998–2003)
(I) (2017)
(2010–2017)
(1966–1969)
(2009– )
(2019)
(1990–1991)
(2021)
(2017–2021)
(2019– )
(2021)
(2012)
(1995)
(2013–2020)
(2020–2021)
(2017)
(2016–2018)
(2020– )
(2017– )
(2020)
(2013–2017)
(2015)
(2019–2020)
(2021)
(2017–2018)
(2020– )
(2021)
(2013–2015)
(2012–2017)
(2015)
(I) (2013–2016)
(2019)
(2020– )
(2003)
(2017)
(2017– )
(2002)
(2019)
(2020)
(I) (2020)
(III) (2021)
(2018)
(2021)
(2009– )
(II) (2016)
(1976)
(1978)
(2021)
(2019– )
(2020– )
(I) (2019)
(2021– )
(2021)
(2016–2019)
(2021)
(2009–2014)
(2021)
(2022)
(2018– )
(2020)
(2018)
(2011–2014)
(2021)
(2007–2013)
(2019)
(2017)
(2016)
(2021)
(2006–2007)
(2002–2007)
(2014–2017)
(I) (2020)
(2013–2017)
(2011–2017)
(2010–2019)
(2021– )
(2021)
(2001)
(2021)
(2008– )
(2021)
(2021– )
(2013–2017)
(2012–2019)
(2018)
(2017)
(2014–2016)
(2009–2012)
(2018–2020)
(2001–2005)
(2017–2021)
(2019)
(2016– )
(2015–2017)
(2011–2015)
(2015)
(2014–2018)
(I) (2019)
(2016–2021)
(2015–2021)
(2002)
(2020– )
(2001)
(2015–2019)
(2018)
(2017–2018)
(1982–1993)
(2018)
(2021)
(1998– )
(2016– )
(2017)
(2015–2018)
(2021– )
(2019– )
(2018– )
(1968)
(2010–2018)
(2014–2021)
(2021– )
(2016– )
(2017–2019)
(2007–2010)
(2016)
(2018–2021)
(2020)
(2020)
(2017)
(2020– )
(1978)
(2014–2019)
(2020)
(2017–2019)
(2011)
(2018– )
(2013–2021)
(2019– )
(1990–1996)
(2004)
(2013–2017)
(2011)
(2021)
(2020– )
(2020)
(2006–2013)
(2007–2014)
(2019– )
(1996–2001)
(2017– )
(2013)
(2020– )
(2014)
(2016)
(2016–2018)
(2017–2021)
(2019)
(I) (2020)
(2016– )
(2021)
(1978)
(2020)
(2021)
(2018–2020)
(2016– )
(2008)
(1999–2000)
(2015–2019)
(2021)
(2015–2019)
(I) (2017)
(2014–2016)
(2019)
(2021– )
(2020–2021)
(2018)
(2012–2014)
(2018)
(2018–2020)
(2014–2018)
(2018– )
(II) (2016)
(I) (2017)
(2019)
(2020– )
(2018)
(I) (2019)
(2019)
(2017)
(2014–2020)
(2017)
(2014–2019)
(I) (2013)
(2020)
(2019)
(2016–2018)
(2020)
(2021– )
(2012)
(2016–2019)
(2016–2020)
(2016–2018)
(2015–2017)
(2020)
(2020)
(2021)
(2016)
(2017)
(2012)
(2011)
(2012–2018)
(2006)
(2019)
(2015–2019)
(2021)
(2018–2019)
(2009–2013)
(2016–2019)
(2020)
(1971)
(2020)
(2004– )
(I) (2013)
(2021)
(1989)
(2016)
(1998)
(2001–2018)
(2021– )
(1987–1995)
(2016–2019)
(I) (2014)
(1998–2020)
(2016–2018)
(2017–2019)
(2017)
(2017)
(2019)
(2018)
(2014– )
(2017–2019)
(2014)
(2012– )
(2021)
(I) (2015)
(2014–2019)
(2004)
(2018–2020)
(I) (2013)
(2005– )
(2018)
(1997)
(2019– )
(2014–2016)
(2021– )
(2004–2013)
(2002– )
(2021)
(2020– )
(2017)
(2018– )
(2018– )
(2016)
(2018)
(2020)
(2019– )
(2019–2020)
(2010)
(2018)
(I) (2016)
(2015)
(2020)
(2018– )
(2015–2019)
(2021– )
(II) (2017– )
(2014–2017)
(2015)
(I) (2020)
(2015– )
(I) (2020)
(1997)
(2018)
(2011– )
(I) (2018)
(I) (2021)
(2016)
(2020)
(2004–2012)
(2021– )
(2021– )
(2019)
(2010– )
(2017)
(2018)
(2019– )
(2015–2019)
(2019–2021)
(2021)
(2012–2018)
(2016–2020)
(2021)
(2020)
(IV) (2020)
(1968)
(2013– )
(2016)
(I) (2017)
(2006–2010)
(2016–2018)
(2021)
(2014–2016)
(2013)
(2006–2012)
(2020– )
(1968)
(2017)
(2015–2018)
(2020)
(2021)
(I) (2017)
(2020)
(2017)
(2019–2021)
(2019)
(1997– )
(2020)
(2013)
(2019)
(2014–2020)
(2013–2015)
(2016)
(1997)
(2020– )
(2016–2018)
(2020– )
(2018)
(2021)
(2019)
(2021)
(2020– )
(1996)
(2020– )
(2021)
(1994–2000)
(2012–2014)
(2016–2018)
(2021– )
(2018)
(2013)
(2018)
(1993)
(2015– )
(2018)
(2020)
(2020)
(2018)
(II) (2020)
(1980)
(2019)
(I) (2011)
(2020)
(2021)
(2016)
(2014)
(1995–1996)
(1975)
(2020)
(2017)
(2019)
(2015–2018)
(2016–2017)
(2019)
(2012– )
(2020)
(2018– )
(2011– )
(2015–2019)
(2021)
(2017)
(2011)
(2017)
(2012)
(I) (2016)
(2019–2020)
(2017–2019)
(2020)
(2018–2019)
(2001)
(2005–2014)
(2013)
(2013–2015)
(1993–1996)
(II) (2019– )
(2016)
(2021)
(2009)
(2018– )
(2019– )
(2017)
(2015)
(2018– )
(2021)
(2010)
(2019)
(2013–2020)
(2021)
(2016)
(2018– )
(2012)
(2019)
(1962)
(1996)
(2015–2018)
(2021)
(2018)
(2011–2015)
(1991)
(2020)
(2016)
(2016–2017)
(2020)
(2020)
(2009)
(2019)
(2020)
(2010)
(2022– )
(2001)
(2014–2018)
(II) (2017)
(I) (2012)
(2014– )
(2020– )
(2018– )
(2015–2019)
(1984)
(2021)
(2011–2016)
(2021– )
(2009–2019)
(2015)
(2021)
(2019)
(2019)
(2015)
(2016)
(II) (2020– )
(2021– )
(2020)
(2021)
(2016)
(2019– )
(2020)
(2019–2021)
(2006–2021)
(I) (2010)
(2000)
(2020)
(2010–2018)
(2016)
(2016–2019)
(2021)
(2018–2019)
(2021)
(2017)
(2020)
(2018)
(2016)
(2011–2019)
(2012)
(2012–2015)
(2020)
(2020– )
(2015)
(2021)
(I) (2013–2014)
(2017)
(2020)
(1960)
(1988)
(1995)
(2021)
(2020)
(2015– )
(2017–2018)
(2007)
(2018– )
(2021– )
(2021)
(1987)
(2021)
(2019)
(2017– )
(2020– )
(I) (2019)
(2006)
(2006)
(2019)
(2019)
(2017)
(2016–2020)
(2019)
(2022)
(2021)
(2018)
(2021)
(2019– )
(2016)
(2010–2011)
(2019– )
(2017–2019)
(2017)
(2018– )
(2015– )
(1969)
(2016– )
(2020)
(2002)
(2021– )
(2021)
(2006–2011)
(2018)
(II) (2019)
(2020– )
(2002)
(2017)
(2017– )
(2018)
(1961)
(2018)
(2021)
(2013)
(2004)
(2015–2019)
(1962)
(2013)
(2017)
(2021– )
(2009)
(2021)
(2018–2019)
(2017–2019)
(2017)
(2021– )
(2021)
(2020–2021)
(1979)
(2020– )
(2017)
(II) (2022)
(2019–2020)
(2019– )
(2011)
(2016)
(2016)
(I) (2017)
(2014–2015)
(2018)
(2006–2011)
(2017–2020)
(2016– )
(2020)
(2019)
(2019)
(2017– )
(2013– )
(2020)
(2016)
(2018– )
(2019)
(2019)
(2015)
(2019)
(2021– )
(2018–2019)
(2020)
(2015)
(2018)
(2011)
(2010– )
(2011)
(2015)
(2020)
(1956)
(2016)
(2014)
(2013)
(2018)
(2011)
(2013)
(2016–2019)
(2020)
(2018)
(2017)
(2019–2021)
(2013–2016)
(2022)
(2021)
(2016–2018)
(III) (2018)
(2018)
(2020)
(2020)
(2014)
(2018)
(2013)
(2020)
(2014)
(2010)
(2020)
(2005)
(2013)
(I) (2019)
(2012)
(2021)
(2018)
(2021)
(2017– )
(II) (2012– )
(2011)
(2021)
(2019)
(2004– )
(1969)
(2018)
(2020– )
(2018–2020)
(2015)
(2020)
(II) (2013)
(2017)
(I) (2015)
(I) (2019)
(1983)
(I) (2013)
(2021)
(2002–2019)
(2020– )
(2014–2016)
(2017)
(2008)
(2016)
(2021– )
(2020)
(2019– )
(2020– )
(2020)
(2020)
(2019)
(2022)
(2020)
(2013)
(2016–2017)
(2019)
(2013–2018)
(2020– )
(2014–2017)
(2014)
(2010)
(2013– )
(2014)
(2022)
(2021– )
(2019)
(2021)
(2020–2021)
(2016–2020)
(2019–2020)
(2020)
(2016)
(2020)
(2005–2008)
(2019)
(1989)
(2022)
(2015)
(2019)
(2010–2020)
(2020)
(2011–2016)
(2017)
(2016)
(2013 TV Movie)
(2020)
(2021)
(2012)
(2016)
(2021– )
(2018)
(2014)
(2021)
(II) (2015)
(2016)
(I) (2012–2015)
(I) (2015)
(2020– )
(1975–1979)
(2016–2018)
(2020)
(2021– )
(2016)
(2019)
(2016)
(2019)
(2005)
(2021– )
(2016–2020)
(2018)
(2021)
(2013–2017)
(1984)
(2013)
(2012)
(1990)
(2021)
(2019–2021)
(2015)
(2020)
nan
(2018–2020)
(I) (2018)
(2021– )
(1997)
(2016)
(2012)
(2017–2020)
(2007)
(2019– )
(I) (2019)
(II) (2018)
(2019– )
(2017)
(2019)
(II) (2018)
(2020)
(2018)
(2016– )
(2008)
(2018)
(I) (2018)
(2019)
(2021– )
(2017–2020)
(2019– )
(2005)
(2016)
(2012)
(2018–2021)
(2020)
(2009)
(IV) (2021)
(2018)
(2018)
(2019)
(2018– )
(2020– )
(2018)
(2017)
(2015–2018)
(I) (2017)
(2018)
(2020)
(2021)
(2018)
(I) (2014)
(2018)
(2019)
(2020)
(2016)
(2017– )
(2011)
(2019– )
(2014–2015)
(2020– )
(2020–2021)
(2021)
(2018)
(2020)
(2020– )
(2018–2020)
(2017)
(I) (2019)
(2013)
(2021– )
(2018– )
(2019– )
(2016–2020)
(2019– )
(2021)
(2019– )
(2021)
(2006)
(2020)
(II) (2016)
(2020)
(2018)
(2021)
(2017– )
(2018)
(2015)
(2021)
(2020)
(2017)
(2016)
(2016)
(2018)
(I) (2017)
(2020)
(1998)
(2018)
(2017–2019)
(2015–2016)
(2016)
(2016)
(2019)
(2019)
(2019)
(2017)
(2021)
(2018)
(2020)
(2020)
(I) (2020)
(2017)
(2019)
(2020)
(2018–2020)
(1995–1998)
(1969)
(II) (2016)
(I) (2012)
(2020)
(2019)
(2011)
(1997)
(2013)
(II) (2018)
(2018–2021)
(2020)
(1986)
(2017)
(2017)
(2019–2020)
(2017)
(2021)
(2006)
(I) (2020)
(2016– )
(2016)
(2021– )
(2019)
(2020)
(1989)
(2019– )
(2019–2020)
(2019)
(2019)
(2015)
(2015–2019)
(2012–2013)
(2018–2020)
(2019)
(2016–2018)
(2020– )
(2018)
(2017–2018)
(2018)
(2021– )
(2019)
(2017–2018)
(2018–2020)
(2016– )
(2021)
(2020– )
(2020)
(2020)
(2012–2014)
(2014–2016)
(2020)
(I) (2017)
(2019)
(2015–2017)
(2010)
(2019)
(2012)
(2017)
(2019)
(I) (2018)
(2020– )
(2018)
(2019)
(1966)
(2015)
(I) (2017)
(2019)
(2011–2012)
(2019)
(2008– )
(2008–2013)
(2012– )
(2018)
(2016–2017)
(2011–2021)
(2016 Video)
(2019)
(2019)
(2021– )
(2012)
(2020)
(2018)
(2019)
(2020– )
(2019)
(2013–2015)
(2014–2019)
(2017 TV Movie)
(2020)
(2009–2011)
(2018)
(2017)
(2004)
(2004–2018)
(1967)
(2018)
(I) (2017)
(I) (2019)
(2021)
(2020)
(I) (2015)
(2013)
(2019– )
(2017)
(2008)
(2021– )
(2018–2020)
(2020)
(1984– )
(2019)
(2012)
(1994)
(I) (2012)
(2019)
(2011–2014)
(2003–2006)
(2016–2020)
(III) (2015)
(2017)
(2014–2016)
(2021– )
(2018)
(2005– )
(2013)
(2020)
(2019)
(1974)
(1995)
(2017– )
(I) (2019)
(2017)
(2010)
(2021)
(2009–2014)
(2021– )
(2018–2020)
(2015–2016)
(2019)
(2014– )
(2018– )
(2020– )
(2016–2019)
(2020)
(2000–2004)
(2020– )
(2021– )
(2021)
(2019)
(2021– )
(1984–2021)
(2021)
(2017)
(2019)
(2019–2020)
(2021)
(2021)
(2010)
(2011–2012)
(2021– )
(2020– )
(2021)
(2010)
(2015–2018)
(2020)
(2020)
(2021– )
(2017–2019)
(I)
(2017)
(I) (2019)
(2018)
(II) (2021)
(2019)
(2012)
(2017–2018)
(1994–1999)
(2017)
(III)
(2021– )
(2016)
(2020– )
(2020– )
(2006–2012)
(2006)
(1992)
(2019– )
(2018)
(2020)
(I) (2017)
(2020– )
(2017–2021)
(2018)
(2017)
(2019– )
(2021– )
(2020)
(2019)
(2021– )
(2021– )
(2018)
(2018– )
(2019– )
(2019)
(2020)
(2019– )
(2020)
(2018)
(2017–2021)
(2013)
(2020)
(2018)
(1969–1974)
(2017)
(2014)
(2019)
(2020– )
(2009)
(III) (2021)
(2014–2019)
(2021)
(2012–2016)
(2020)
(2013–2014)
(I) (2008)
(2019)
(2020)
(2018–2019)
(2014–2016)
(2014)
(2019)
(1958)
(2022)
(2020)
(I) (2015)
(2020)
(2020– )
(2019–2021)
(2013)
(2013–2014)
(2020)
(2020)
(2021– )
(2021)
(2017)
(2020– )
(2008–2009)
(2018– )
(2019)
(2016)
(II) (2004)
(2016–2017)
(2019–2021)
(2019)
(2021)
(2021– )
(2017)
(2018)
(2014)
(2014)
(2019)
(2020– )
(2017)
(2018– )
(2020– )
(2017–2019)
(2017)
(1993)
(2017)
(2021)
(2019)
(2013)
(III) (2019)
(2020– )
(2017– )
(2019)
(2017)
(2014)
(2019)
(2017)
(2017)
(2021– )
(2020)
(2021– )
(2020)
(I) (2017)
(2019)
(2019–2020)
(2018)
(2018–2020)
(2021)
(2020– )
(2016)
(2020)
(2016)
(2017–2020)
(2018)
(2002)
(2020)
(2016)
(2017)
(2018– )
(2020– )
(2019)
(2006–2009)
(2020)
(2011–2014)
(2004)
(2017)
(2011)
(2011)
(2011)
(2011–2013)
(2007–2008)
(1988–1999)
(2014)
(2019–2020)
(2021)
(2011–2018)
(2020)
(2021– )
(2020)
(2005)
(2012–2020)
(I) (2012)
(2020– )
(2021)
(2021)
(2020– )
(2016)
(2018)
(2019)
(2013)
(2016)
(2010–2012)
(2018– )
(2021)
(2018)
(2018– )
(2010–2014)
(2018)
(2009)
(2019– )
(2020)
(2012–2014)
(2016– )
(2020)
(2007)
(2021)
(2018)
(2008–2009)
(2021– )
(2019–2021)
(2016 Video)
(2019)
(2019)
(2012)
(2019– )
(I) (2021)
(II) (2012)
(2013–2014)
(2019)
(2020)
(2021)
(2018)
(1932)
(2019– )
(2014 TV Movie)
(2021)
(2018)
(2011–2012)
(2016)
(I) (2014)
(2017)
(2012– )
(2018)
(2018)
(2016)
(2015)
(2015)
(2021)
(2015)
(2013)
(2020)
(2019)
(2016)
(1941)
(2019– )
nan
(2021)
(2015)
(2022– )
(2015)
(2021– )
(2019)
(2012)
(2020)
(2015)
(2017–2018)
(2020– )
(2020)
(2017)
(2020)
(2018–2020)
(2021)
(I) (2015)
(2006– )
(2003)
(2018– )
(2021)
(2016–2017)
(II) (2013)
(2020)
(2020)
(2017)
(2017)
(2018)
(2020– )
(2007)
(2021– )
(2016–2018)
(2017)
(2015)
(2004– )
(2014– )
(2015–2017)
(2022)
nan
(2016–2018)
(2014–2015)
(2018)
(2017)
nan
(2017)
(2018)
(1992–1995)
(2017– )
(2017–2018)
nan
(2018)
(2015)
nan
(2015–2016)
(2016)
(2019)
(2020)
(2022)
(2016–2017)
(2019)
(I) (2019)
(2020)
(2020)
(2012– )
(II) (2017)
(2019–2021)
(2021– )
(2012)
(2012–2013)
(2018)
(2016–2017)
(2016)
(2020)
(2015)
(2017)
(2014– )
(2022– )
(2018)
(2021)
(2015–2019)
(1991)
(2017)
(2017)
(2019)
(2020)
(2020)
(2016)
(2019–2021)
nan
(2018– )
(2016 TV Special)
(2012)
(2020)
(2021)
(2018– )
(2021– )
(2020 TV Movie)
(2012)
(2020– )
(2018)
(2012)
(2020– )
(2018)
(2018)
(2021)
(2008–2010)
(2020)
(2019)
(2011–2012)
nan
(2016)
(2017– )
(2018– )
(2006)
(2021)
(2021)
nan
(2006)
nan
(2018)
(2017)
(2018)
(2016)
(2018– )
(2020– )
(2019)
(I) (2015)
(2016–2017)
(2020)
(2013)
(2016)
nan
(2015)
(2018– )
(2017)
(2017)
(2015)
(2018)
(2017)
(2015– )
(2017–2019)
(2017)
(2012)
(I) (2018)
(1996–2001)
(2018– )
(2015)
(2019– )
(2016)
(2018)
(1966)
(II)
(2021– )
(2020)
nan
(2020 Video)
(1999– )
(2019)
(2014)
(2020–2021)
(2017)
(2017)
(2018)
(2018)
(2020– )
(2021– )
(1950)
(2014)
(2017)
(I) (2018)
(2017)
(2002)
(2021)
(2017)
(2017– )
(2018)
(2020)
(2021)
(2013–2018)
(2019)
(2017)
(2018)
(2020)
(2018)
(2020 TV Special)
(2021– )
(2019)
(2019– )
(2016)
(2017)
(2015–2021)
(2019)
(2019– )
(2020)
(2007)
(2018– )
(2020)
(2016)
(2018)
(2014)
(2019)
(2020)
(1992–2014)
(2020)
(2021)
(2019)
(2021)
(2020– )
(2021)
(II) (2015)
(2018)
nan
(2020– )
(2017–2018)
(2020)
(2020– )
(I) (2018)
(2018)
(2014)
(2002–2005)
(I) (2011)
(2013 TV Special)
(2017)
(2016)
(2020– )
(2018– )
(2010–2014)
(2017)
(2020)
(2017–2018)
(2019– )
(2021)
(2017)
(2011)
(1990)
(I) (2021– )
(2009)
(2018)
(2006)
(2018–2020)
(2020)
(2021)
(2017)
(2008– )
(2018–2019)
(2021)
(2020)
nan
(2015)
(2020)
(2020)
(2012–2016)
(2010)
(2017–2018)
(2017–2019)
(1999)
(2019)
(2016 TV Movie)
(2019)
(2017–2019)
(I) (2013)
(2016–2017)
(2019)
(2017)
(2018)
(2017–2018)
(2020)
(1998)
(2022– )
(XII)
(2019)
(2018)
(2017– )
(2020)
(2020– )
(I) (2017)
(2022)
(2018)
(2020)
(1978)
(2021)
(2018)
nan
(2015)
(2018)
(2021)
(2019)
(2006)
nan
(2018– )
(2020)
(2014– )
(2018)
(2017)
(2020)
(2022)
(2012)
(2016)
(2018– )
(2014)
(2010–2011)
(2020)
(2020)
(2019)
(2016)
(2021)
(2019)
(2020)
(II)
(2018)
(2018)
(2013)
(2016)
(2021)
(2020)
(2019)
(2021)
(2018)
(2019)
(2021)
(2020)
(2020)
(2019–2020)
(2020)
(2020)
(2015– )
(2018)
(VII)
(2016)
(2003–2006)
(2021– )
(2019)
(2020)
(2021– )
(2019)
(I) (2019)
(2016)
(2020– )
(2017)
(2017)
(2021– )
(2020)
(2020)
(2019)
(2017)
(2020)
(2018)
(2017)
(2021)
(2018– )
(2019– )
(2018)
(2018)
(I) (2016)
(2021– )
(2014– )
(2021)
(2020– )
(2021– )
(2011)
(I) (2018)
(2019)
(2011)
(2018)
(1994)
(2021– )
(2020)
(2018)
(2019– )
(2021– )
(2007)
(1994)
(2021 TV Movie)
(2015)
(1983– )
(2020– )
(2022)
(2005)
(2017)
(2021– )
(2022)
(1996 Video)
(I) (2016)
(2012–2013)
(2022)
(2018– )
(2012)
nan
(2020)
nan
nan
(2013 TV Movie)
(2019–2020)
(1994)
(2018)
(2019)
(2017– )
(2016)
nan
(2012–2014)
(2017– )
(2012)
(2021)
(2022)
(2020)
(1993 TV Movie)
(2018 TV Movie)
(2020)
(2018)
(2019)
(2018– )
(2013 TV Movie)
(2005)
(2021– )
(2020)
(2016 TV Movie)
(2021)
(1999–2000)
(2019)
(II) (2018)
(2016)
(I) (2011)
(2018)
(2020)
nan
(2019)
nan
(2012–2017)
(2021)
(I) (2019)
(2018–2019)
(2010– )
(2014 TV Movie)
(2016)
(2020)
(2017)
(2018)
(2016)
(2016– )
(2019– )
(2017–2019)
(2019)
nan
(2019)
(2021– )
(2018)
(2016)
(2018)
(2012)
(2019)
(2018)
(2016)
(2018– )
(2016)
(2015– )
(2016–2020)
(2012)
(2018– )
(2015–2018)
(2015)
(2005–2009)
(2012)
(I) (2017)
(2016)
(2019)
nan
(2019)
(2019)
(2015–2017)
(2021– )
(2021– )
(2021– )
(2017)
(2017–2018)
(2021)
(2021)
(2005)
(2021– )
(2016–2019)
(2019)
(2016)
(2017)
(2007)
nan
(2020– )
(2018)
(2018– )
nan
(2019)
(2021)
(2004)
(2018)
(2019)
(2020)
(1993)
(2016)
(2020)
(2018)
(2020)
(2021)
(2016)
(2014 TV Movie)
(I) (2014)
(2018)
(2020– )
(2017)
(2017– )
(2019– )
(2017)
(2020)
(2016– )
(2018– )
(2018– )
(2019– )
(2019)
(2021– )
(2022)
(2012– )
(2020– )
(2018– )
nan
nan
(2011–2013)
(2021– )
(2016–2019)
(2015– )
(2013–2014)
(2021– )
(2017)
(2017)
(2009–2014)
(2021– )
(2007)
(2016–2017)
(2018–2020)
(2012)
(2019)
(2015)
nan
(2019)
nan
(2019– )
(2015–2018)
(2018)
(2010)
(2019)
(2018)
(2014– )
(2001–2002)
(II) (2019)
(2019)
(2013– )
(2016)
(2018)
(2020)
(2015 TV Movie)
(2018)
(2012)
(I) (2016)
(2016)
(2015)
(2019– )
(2017)
(2019– )
(2020– )
(2019)
(2021– )
(2020– )
(2022)
(I) (2020– )
(2019)
(2020)
(I) (2020– )
(2018– )
(2017)
(2019– )
(2017–2018)
(2011 Video)
(2020)
(2020– )
(2016–2019)
(2011– )
(2018)
(2008 Video)
(2012 Video)
(2018– )
(2018)
(2015)
(2017)
(2020)
(2019)
(2020– )
(2021)
(2020– )
(2016)
(2018– )
(2018)
(2020)
(2018)
(2018)
(2019)
(2020)
(2013)
(2018)
(2019)
(2018)
(II)
(2022)
(2019)
(2018)
(2019– )
(2015– )
(2018– )
(2019)
(2019)
(2017)
(2016)
nan
(2019– )
(2021)
(2020)
(2017– )
(2014)
(2013–2017)
(2020– )
(2019)
(2018–2021)
(2016)
(2020– )
(2007)
(2017)
(2020– )
(2018)
(2009–2016)
(2021)
(2015)
(2020)
(2009)
(2016– )
(2015)
(2020)
(I) (2018)
(2019)
(2019)
(2012–2015)
(2021– )
(2019)
(2019)
(2020)
(2021)
(1997)
(2014–2017)
(2020– )
(2021– )
(2020)
(2018–2020)
(2021)
(2010)
(2015–2016)
(2018– )
(2016– )
(2017)
(2010– )
(2016)
(2018)
(2015– )
(2012)
(2020)
(2019)
(2018–2019)
(2019)
(2019)
(2021)
(I) (2019)
(2018 TV Movie)
(2017)
(2020)
(2020)
(2022)
nan
(2020– )
(2019)
(2020)
(2020)
(1946)
(2019–2020)
(2019)
(2016–2018)
(II) (2014)
(2019 Video)
(2017)
(2010)
(2020)
nan
(2017– )
(2020)
(2019)
(2020)
(I) (2011)
(2017– )
(2019)
(I) (2014)
(2020)
(2014–2017)
(2012–2014)
(2013)
(2020– )
(2016)
(2020)
(2014– )
(2020– )
(2017– )
(2019)
nan
(2019–2021)
nan
(2016–2021)
(2020–2021)
(2022)
(2020)
(2020)
(2020– )
(2013)
(2019–2020)
(1981–1989)
(2022)
(2016– )
(2019)
(2019– )
(2020)
(2019– )
(IV) (2016)
(2017)
(2018)
(2020)
(2017)
(2021– )
(2015– )
(2014)
(2017)
(2020– )
(2018)
(2017–2018)
(2021)
(2015)
(2018)
nan
(2021)
nan
(2021– )
nan
(2019)
(2017)
(2021)
(2013)
(I) (2020)
(2019)
(2017)
(III) (2016)
(2016)
(2016)
(2017–2018)
(2020)
(2018)
(2015)
(2016)
(2019 TV Movie)
(2016)
(2017)
(2021 TV Movie)
(2018)
(1952)
(2003–2006)
(2016– )
(2020)
(2018)
(2016–2018)
(2007 Video)
(2017)
(2021– )
(2020– )
(I) (2018)
(2020)
(2015)
(2019)
(2018– )
(2019)
(2008)
nan
(2016)
(2015– )
(2021)
(2018–2019)
(2020– )
(2011–2012)
(2018)
(I) (2021)
(I) (2019)
(2020)
nan
(2016)
nan
(2021)
(2019– )
(2014)
(2017– )
(2020)
(2014)
(2018)
(2019)
(2016–2017)
(2017)
(2020)
(2020– )
(2019)
(2016)
(2018)
(2020)
(1998– )
(2018– )
(2019)
(2020)
(2019)
(2018– )
(II) (2018)
(2018)
(2021)
(2020)
(2021)
(2000–2014)
(2016–2018)
(2020)
(2021– )
(2016)
(2020)
(2013)
(2019)
(2019– )
(2010– )
nan
(2018– )
(2018– )
(II) (2016)
(III) (2019)
(2021– )
(2019)
(2018)
(2019)
(2015)
(2020– )
(2019– )
(2016)
(2019– )
(2020)
(2018)
(2021– )
(2020)
(2019)
(2020)
(2018)
(2021– )
(2020)
(2019– )
(2020– )
(2017)
(2021)
(2020)
(2017)
(1992– )
(2014)
(2004)
(2020)
(2016– )
(2017)
(2020)
(2020– )
(2018)
(2020)
(2021)
(2019)
(2015)
(2017)
(2011–2012)
nan
(2016)
(2018)
(1957)
(2019)
(2018– )
(1996)
(2017)
(2015– )
(2018)
(2018– )
(2018)
(2017)
(2016)
(2007)
(2003–2007)
(2018)
(II) (2020)
(III) (2015)
(I) (2016)
(2020)
(2019– )
(2018)
(2018– )
(2012– )
(2018)
(2012– )
(2018)
(2022)
(2018– )
(2015– )
(2017)
(2019– )
(2021)
(2019)
(2018– )
(IV)
(2018– )
(2012)
(2018– )
(2021– )
(2020)
(2018)
(2018–2020)
(2017)
(2018)
(2017)
(2018)
(2021)
(2018)
(2020– )
(2019)
(2017)
(2018)
(2015)
(2018)
(2018–2019)
(2014)
(2021)
(2017)
(2008–2017)
(2018– )
(2015)
(2018)
(2017)
(2021– )
(2020)
(2021– )
(2020)
(2016)
(2019)
(2020)

AttributeError: 'DataFrame' object has no attribute 'isNaN'